## ==================================================
## local1(local test) - DB connect to local docker container
## ==================================================

server:
  port: 8082

spring:
  ## ==============================================================================
  ## DB(Redis) 
  ## ==============================================================================
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300

  ## ==============================================================================
  ## DB(PostgreSQL) Connection 
  ## ==============================================================================
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=es-test
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    ## --------------------------------------------------------------
    hikari:
      # 最小空閒連接數
      minimum-idle: 10
      # 連接池最大大小
      maximum-pool-size: 50
      # 連接最大空閒時長
      idle-timeout: 60000
      # 連接生命時長
      max-lifetime: 1800000
      # 連接的超時時長
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ## ==============================================================================
  ## Quartz
  ## ==============================================================================
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:db/tables_postgres.sql
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      
#   properties:
#     org:
#       quartz:
#         scheduler:
#           instanceName: quartzScheduler
#           skipUpdateCheck: true
#         dataSource:
#           quartzDataSource:
#             driver: org.postgresql.Driver
#             URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=es-test
#             user: postgres
#             password: postgres
#             maxConnections: 30
#             provider: hikaricp
#         jobStore:
#           isClustered: false
#           useProperties: false
# #            class: org.springframework.scheduling.quartz.JobStoreCMT
#           class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
#           driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
# #            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#           dataSource: quartzDataSource
#           tablePrefix: qrtz_
#           misfireThreshold: 60000
#         threadPool:
#           class: org.quartz.simpl.SimpleThreadPool
#           threadCount: 30
#           threadPriority: 5
#           threadsInheritContextClassLoaderOfInitializingThread: true